ktor:
  application:
    modules:
      - com.adam.buru.ApplicationKt.module
  deployment:
    port: 8081
  database:
      url: "jdbc:h2:file:./database/timemanager_db;MODE=MySQL;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE"
      driver: "org.h2.Driver"
      user: "root"
      password: ""
jwt:
  audience: "my-audience"
  issuer: "my-issuer"
  realm: "my-realm"
  secret: "secretpassword"